<a href="{{ route('welcome') }}" wire:navigate
    class="{{ request()->routeIs('welcome') ? 'text-red-600 font-bold' : 'text-gray-900 font-bold hover:text-red-600 transition-colors' }}">{{ __('Home') }}</a>
<a href="{{ route('events') }}" wire:navigate
    class="{{ request()->routeIs('events') ? 'text-red-600 font-bold' : 'text-gray-900 font-bold hover:text-red-600 transition-colors' }}">{{ __('Events') }}</a>
<a href="{{ route('articles') }}" wire:navigate
    class="{{ request()->routeIs('articles') ? 'text-red-600 font-bold' : 'text-gray-900 font-bold hover:text-red-600 transition-colors' }}">{{ __('Articles') }}</a>
{{-- <a href="{{ route('projects') }}" wire:navigate
    class="{{ request()->routeIs('projects') ? 'text-red-600 font-bold' : 'text-gray-900 font-bold hover:text-red-600 transition-colors' }}">{{ __('Projects') }}</a> --}}
{{-- <a href="{{ route('forum') }}" wire:navigate
    class="{{ request()->routeIs('forum') ? 'text-red-600 font-bold' : 'text-gray-900 font-bold hover:text-red-600 transition-colors' }}">{{ __('Forum') }}</a> --}}
